apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmaps/app-config.yaml
  - secrets/app-secrets.yaml
  - databases/postgres.yaml
  - databases/mongodb.yaml
  - databases/rabbitmq.yaml
  - databases/db-init-job.yaml
  - deployments/user-service.yaml
  - deployments/resource-service.yaml
  - deployments/reservation-service.yaml
  - deployments/notification-service.yaml
  - deployments/frontend.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml
  - ingress.yaml
